[package]
name = "sqler-task"
version.workspace = true
edition.workspace = true

[dependencies]
sqler-core.workspace = true

serde.workspace = true
serde_json.workspace = true

tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true

chrono = "0.4"
